# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SSBouncyButtonDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SSBouncyButtonDemo
  pod 'BRYSerialAnimationQueue', '~> 1.0'
  pod 'UIColor-Hex'
  pod 'UIImage+BetterAdditions', '~> 2.0'

end
